# Generated by Django 4.2.17 on 2025-06-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=100, unique=True, verbose_name='Descrição do exercício *')),
                ('tempo', models.IntegerField(default=10, help_text='Procure manter o tempo entre 5 e 60 segundos.', verbose_name='Tempo de execução (em segundos) *')),
                ('intensidade', models.CharField(choices=[('25', '25%'), ('50', '50%'), ('75', '75%'), ('100', '100%')], default='25', help_text='A intensidade do exercício', max_length=3, verbose_name='Intensidade *')),
                ('video', models.URLField(blank=True, max_length=100, null=True, verbose_name='Link do video')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o exercício pode ser usado no sistema.', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'exercicio',
                'verbose_name_plural': 'exercicios',
                'ordering': ['-is_active', 'descricao'],
            },
        ),
    ]
