# Generated by Django 4.2.17 on 2025-06-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data consulta. Use o formato dd/mm/aaaa.', verbose_name='Data consulta')),
                ('hora', models.TimeField(help_text='Hora consulta. Use o formato hh:mm.', verbose_name='Hora consulta')),
                ('comentarios', models.TextField(blank=True, help_text='Comentários sobre a consulta.', max_length=2000, null=True, verbose_name='Comentários')),
                ('realizado', models.BooleanField(default=False, help_text='Se a consulta foi realizada.', verbose_name='Realizado')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, a consulta encontrará na agenda do paciente.', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('fisioterapeuta', models.ForeignKey(help_text='* Campo obrigatório. Fisioterapeuta no atendimento.', on_delete=django.db.models.deletion.RESTRICT, related_name='fisioterapeuta_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta *')),
                ('paciente', models.ForeignKey(help_text='* Campo obrigatório. Paciente na consulta ou agenda.', on_delete=django.db.models.deletion.RESTRICT, related_name='paciente_agenda', to=settings.AUTH_USER_MODEL, verbose_name='Paciente *')),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
                'ordering': ['-is_active', '-data', '-hora'],
                'unique_together': {('paciente', 'fisioterapeuta', 'data', 'hora')},
            },
        ),
    ]
