# Generated by Django 4.2.17 on 2025-06-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=100, unique=True, verbose_name='Título *')),
                ('texto', models.TextField(blank=True, help_text='* Campo obrigatório', verbose_name='Texto *')),
                ('arquivo', models.FileField(help_text='Utilize arquivo .PDF', upload_to='midias', verbose_name='Arquivo PDF de para avaliação (sem autores e identificação)')),
                ('data', models.DateField(auto_now_add=True, help_text='* Campo obrigatório', verbose_name='Data *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, a renda pode ser usada no sistema.', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Autor responsável pela submissão *')),
            ],
            options={
                'verbose_name': 'artigo',
                'verbose_name_plural': 'artigos',
                'ordering': ['-is_active', 'titulo'],
            },
        ),
    ]
