# Generated by Django 4.2.17 on 2025-06-16 17:13

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renda', '0001_initial'),
        ('instituicao', '0001_initial'),
        ('profissao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('SECRETARIA', 'Secretária'), ('PACIENTE', 'Paciente')], default='MEMBRO', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('sexo', models.CharField(choices=[('FEMININO', 'Feminino'), ('MASCULINO', 'Masculino'), ('NÃO DESEJA INFORMAR', 'Não deseja informar')], help_text='* Campos obrigatórios', max_length=20, verbose_name='Sexo *')),
                ('data_nascimento', models.DateField(blank=True, help_text='Use o formato dd/mm/aaaa', null=True, verbose_name='Data de nascimento *')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('celular', models.CharField(help_text='Use DDD, por exemplo 55987619832', max_length=14, verbose_name='Número celular com DDD *')),
                ('cpf', models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='CPF *')),
                ('aceita_termo', models.BooleanField(default=False, help_text='Se marcado, usuário tem consentimento de uso do sistema', verbose_name='Marque o aceite do termo de consentimento')),
                ('escolaridade', models.CharField(blank=True, choices=[('NÃO ALFABETIZADO', 'Não alfabetizado'), ('ENSINO FUNDAMENTAL INCOMPLETO', 'Ensino Fundamental incompleto'), ('ENSINO FUNDAMENTAL COMPLETO', 'Ensino Fundamental completo'), ('ENSINO MÉDIO INCOMPLETO', 'Ensino Médio incompleto'), ('ENSINO MÉDIO COMPLETO', 'Ensino Médio completo'), ('ENSINO SUPERIOR INCOMPLETO', 'Ensino Superior incompleto'), ('ENSINO SUPERIOR COMPLETO', 'Ensino Superior completo'), ('PÓS GRADUAÇÃO', 'Pós Graduação'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado')], help_text='* Campos obrigatórios', max_length=30, null=True, verbose_name='Escolaridade *')),
                ('possui_filhos', models.CharField(blank=True, choices=[('SIM COM ATENÇÃO', 'Sim, tem filhos que demandam atenção'), ('SIM SEM ATENÇÃO', 'Sim, tem filhos mas que NÃO demandam atenção'), ('NÃO POSSUI', 'Não tem filhos')], help_text='* Campos obrigatórios', max_length=15, null=True, verbose_name='Possui filhos *')),
                ('jornada_trabalho', models.CharField(blank=True, choices=[('NENHUMA', 'Não está trabalhando atualmente'), ('ATE 10 HORAS', 'Até 10 horas'), ('DE 11 A 20 HORAS', 'De 11 a 20 horas'), ('DE 21 A 30 HORAS', 'De 21 a 30 horas'), ('DE 31 A 40 HORAS', 'De 31 a 40 horas'), ('MAIS DE 40 HORAS', 'Mais de 40 horas')], help_text='* Campos obrigatórios', max_length=20, null=True, verbose_name='Jornada de trabalho *')),
                ('is_active', models.BooleanField(default=False, help_text='Se ativo, o usuário tem permissão para acessar o sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instituicao', to='instituicao.instituicao', verbose_name='Clínica do usuário (profissional ou paciente)')),
                ('profissao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profissao', to='profissao.profissao', verbose_name='Profissão do usuário')),
                ('renda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renda', to='renda.renda', verbose_name='Renda do usuário')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['-tipo', 'nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('fisioterapeutas', usuario.models.FisioterapeutaAtivoManager()),
                ('pacientes', usuario.models.PacienteAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
                ('pacientes_ativos', usuario.models.PacienteAtivoManager()),
            ],
        ),
    ]
