# Generated by Django 4.2.17 on 2025-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FISIOTERAPEUTA', 'Fisioterapeuta'), ('SECRETARIA', 'Secretária'), ('PACIENTE', 'Paciente')], default='PACIENTE', help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do usuário *'),
        ),
    ]
