# Generated by Django 4.2.17 on 2025-06-16 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercicio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_index=True, help_text='* Campo obrigatório. Tente expressar a ideia geral do treino.', max_length=100, unique=True, verbose_name='Descrição do treino *')),
                ('pausas', models.IntegerField(blank=True, help_text='Pausas entre os exercícios.', null=True, verbose_name='Pausas em segundos')),
                ('data_inicio', models.DateField(blank=True, help_text='Data de início do treino.', null=True, verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término do treino.', null=True, verbose_name='Data de término')),
                ('realizado', models.BooleanField(default=False, help_text='Se o treino foi realizado pelo paciente.', verbose_name='Realizado')),
                ('quantidade_vezes', models.IntegerField(blank=True, help_text='Quantidade de vezes que o treino deve ser realizado.', null=True, verbose_name='Quantidade de vezes a fazer')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o exercício pode ser usado no sistema.', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('exercicios', models.ManyToManyField(help_text='* Campo obrigatório. Exercícios que compõem o treino.', related_name='exercicios', to='exercicio.exercicio', verbose_name='Exercícios *')),
                ('fisioterapeuta', models.ForeignKey(help_text='* Campo obrigatório. Fisioterapeuta que prescreveu o treino.', on_delete=django.db.models.deletion.RESTRICT, related_name='fisioterapeuta', to=settings.AUTH_USER_MODEL, verbose_name='Fisioterapeuta *')),
                ('paciente', models.ForeignKey(help_text='* Campo obrigatório. Paciente que receberá o treino.', on_delete=django.db.models.deletion.RESTRICT, related_name='paciente', to=settings.AUTH_USER_MODEL, verbose_name='Paciente *')),
            ],
            options={
                'verbose_name': 'treino',
                'verbose_name_plural': 'treinos',
                'ordering': ['-is_active', 'descricao'],
            },
        ),
    ]
