# Generated by Django 4.2.17 on 2025-06-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='quantidade_vezes',
        ),
        migrations.AddField(
            model_name='treino',
            name='quantidade_repeticoes',
            field=models.IntegerField(blank=True, help_text='Quantidade de repetições que o treino deve ser realizado no período.', null=True, verbose_name='Quantidade de repetições'),
        ),
    ]
