# Generated by Django 4.2.17 on 2025-06-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0002_remove_treino_quantidade_vezes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='quantidade_vezes_periodo',
            field=models.IntegerField(blank=True, help_text='Vezes que o treino deve ser realizado no período entre a data de início e a data de término. Se não for preenchido, o treino será realizado apenas uma vez.', null=True, verbose_name='Quantidade de vezes o treino deve ser realizado no período'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='quantidade_repeticoes',
            field=models.IntegerField(blank=True, help_text='Quantidade de repetições de cada exercício no treino.', null=True, verbose_name='Quantidade de repetições'),
        ),
    ]
