# Generated by Django 4.2.17 on 2025-06-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0003_treino_quantidade_vezes_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='pausas',
            field=models.IntegerField(default=0, help_text='Pausas entre os exercícios. O valor deve ser em segundos. Se não for preenchido, o treino será realizado sem pausas entre os exercícios.', null=True, verbose_name='Pausas em segundos'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='quantidade_repeticoes',
            field=models.IntegerField(default=1, help_text='Quantidade de repetições de cada exercício no treino. No mínimo, deve ser 1. Se não for preenchido, o treino será realizado apenas uma vez.', null=True, verbose_name='Quantidade de repetições'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='quantidade_vezes_periodo',
            field=models.IntegerField(default=1, help_text='Vezes que o treino deve ser realizado no período entre a data de início e a data de término. Se não for preenchido, o treino será realizado apenas uma vez.', null=True, verbose_name='Quantidade de vezes o treino deve ser realizado no período'),
        ),
    ]
