# Generated by Django 4.2.17 on 2025-06-24 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0004_alter_treino_pausas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreinoExecucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(help_text='* Campo obrigatório. Data e hora em que o treino foi realizado.', verbose_name='Data e horade execução *')),
                ('observacao', models.TextField(blank=True, help_text='Observações sobre a execução do treino.', null=True, verbose_name='Alguma observação para o fisioterapeuta?')),
                ('treino', models.ForeignKey(help_text='* Campo obrigatório. Treino que foi realizado.', on_delete=django.db.models.deletion.RESTRICT, related_name='treino_executado', to='treino.treino', verbose_name='Treino *')),
            ],
            options={
                'verbose_name': 'treino execução',
                'verbose_name_plural': 'treinos execuções',
                'ordering': ['-data_hora'],
            },
        ),
    ]
