# Generated by Django 4.2.17 on 2025-06-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0005_treinoexecucao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinoexecucao',
            name='data_hora',
            field=models.DateTimeField(auto_now=True, verbose_name='Data e horade execução *'),
        ),
    ]
